volumes:
  pgdata:

networks:
  minimyini-backend:
    name: minimyini-backend
  nginx-proxy:
    name: nginx-proxy

services:
  db:
    container_name: minimyini-db
    image: postgres:14-alpine
    restart: on-failure
    expose:
      - "5432"
    networks:
      - minimyini-backend
    environment:
      POSTGRES_DB: minimyini_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data

  minimyini:
    image: minimyini-image
    restart: on-failure
    expose:
      - "8080"
    networks:
      - minimyini-backend
      - nginx-proxy
    depends_on:
      - db
    environment:
      DB_HOST: minimyini-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      VIRTUAL_PORT: 8080

