spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${CLIENT_ID}
                        client-secret: ${CLIENT_SECRET}
                        redirect-url: http://localhost:8080/login/oauth2/code/google
                        code-exchange-url: https://accounts.google.com/o/oauth2/token
                        grant-type: authorization_code
                        scope:
                            - email
                            - profile
                            - https://www.googleapis.com/auth/calendar
                            - https://www.googleapis.com/auth/calendar.events

    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/minimyini_db
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate.ddl-auto: none

    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yml
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

security:
    jwt:
        secret: secret
        expire-time: 9999999