spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/minimyini_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: update

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

security:
  jwt:
    secret: secret
    expire-time: 9999999