volumes:
  pgdata:

networks:
  minimyini-backend:
    name: minimyini-backend
  nginx-proxy:
    external:
      name: nginx-proxy

services:
  db:
    container_name: minimyini-db
    image: postgres:12-alpine
    restart: on-failure
    expose:
      - "5432"
    networks:
      - minimyini-backend
    environment:
      POSTGRES_DB: minimyini_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

  minimyini:
    image: image-name
    restart: on-failure
    expose:
      - "8080"
    networks:
      - minimyini-backend
      - nginx-proxy
    depends_on:
      - db
    environment:
      DB_HOST: minimyini-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: $DB_PASSWORD
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      VIRTUAL_HOST: $HOSTNAME
      LETSENCRYPT_HOST: $HOSTNAME
      LETSENCRYPT_EMAIL: $EMAIL
      VIRTUAL_PORT: 8080

